
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (1,'آذربایجان شرقی','3');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (2,'آذربایجان غربی','4');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (3,'اردبیل','24');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (4,'اصفهان','10');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (5,'البرز','30');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (6,'ایلام','16');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (7,'بوشهر','18');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (8,'تهران','23');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (9,'چهارمحال وبختیاری','14');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (10,'خراسان جنوبی','29');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (11,'خراسان رضوی','9');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (12,'خراسان شمالی','28');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (13,'خوزستان','6');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (14,'زنجان','19');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (15,'سمنان','20');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (16,'سیستان وبلوچستان','11');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (17,'فارس','7');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (18,'قزوین','26');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (19,'قم','25');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (20,'کردستان','12');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (21,'کرمان','8');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (22,'کرمانشاه','5');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (23,'کهگیلویه وبویراحمد','17');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (24,'گلستان','27');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (25,'گیلان','1');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (26,'لرستان','15');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (27,'مازندران','2');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (28,'مرکزی','0');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (29,'هرمزگان','22');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (30,'همدان','13');
INSERT INTO `province` (`id`, `name`,`amar_code`) VALUES (31,'یزد','21');
/*!40000 ALTER TABLE `province` (`id`, `name`,`amar_code`) ENABLE KEYS */;