INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (1,'آبادان',13,'601');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (2,'آباده',17,'701');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (3,'آبدانان',6,'1606');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (4,'آبیک',18,'2604');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (5,'آذرشهر',1,'321');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (6,'آرادان',15,'2006');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (7,'آران وبیدگل',4,'1018');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (8,'آزادشهر',24,'2710');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (9,'آستارا',25,'101');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (10,'آستانه اشرفیه',25,'102');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (11,'آشتیان',28,'2');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (12,'آغاجاری',13,'626');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (13,'آق قلا',24,'2708');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (14,'آمل',27,'201');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (15,'آوج',18,'2606');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (16,'ابرکوه',31,'2107');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (17,'ابوموسی',29,'2201');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (18,'ابهر',14,'1901');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (19,'اراک',28,'1');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (20,'اردبیل',3,'2401');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (21,'اردستان',4,'1001');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (22,'اردکان',31,'2101');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (23,'اردل',9,'1405');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (24,'ارزوییه',21,'823');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (25,'ارسنجان',17,'717');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (26,'ارومیه',2,'401');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (27,'ازنا',26,'1507');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (28,'استهبان',17,'702');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (29,'اسدآباد',30,'1306');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (30,'اسفراین',12,'2801');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (31,'اسکو',1,'322');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (32,'اسلام آبادغرب',22,'501');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (33,'اسلامشهر',8,'2310');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (34,'اشتهارد',5,'3005');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (35,'اشکذر',31,'2108');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (36,'اشنویه',2,'413');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (37,'اصفهان',4,'1002');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (38,'اصلاندوز',3,'2411');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (39,'اقلید',17,'703');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (40,'البرز',18,'2605');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (41,'الیگودرز',26,'1501');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (42,'املش',25,'113');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (43,'امیدیه',13,'616');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (44,'انار',21,'820');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (45,'اندیکا',13,'621');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (46,'اندیمشک',13,'602');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (47,'اوز',17,'736');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (48,'اهر',1,'302');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (49,'اهواز',13,'603');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (50,'ایجرود',14,'1906');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (51,'ایذه',13,'604');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (52,'ایرانشهر',16,'1101');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (53,'ایلام',6,'1601');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (54,'ایوان',6,'1607');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (55,'بابل',27,'202');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (56,'بابلسر',27,'216');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (57,'باخرز',11,'937');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (58,'باشت',23,'1707');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (59,'باغ ملک',13,'615');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (60,'بافت',21,'801');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (61,'بافق',31,'2102');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (62,'بانه',20,'1201');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (63,'باوی',13,'624');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (64,'بجستان',11,'931');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (65,'بجنورد',12,'2802');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (66,'بختگان',17,'735');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (67,'بدره',6,'1610');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (68,'برخوار',4,'1022');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (69,'بردسکن',11,'923');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (70,'بردسیر',21,'810');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (71,'بروجرد',26,'1502');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (72,'بروجن',9,'1401');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (73,'بستان آباد',1,'313');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (74,'بستک',29,'2209');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (75,'بشاگرد',29,'2213');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (76,'بشرویه',10,'2908');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (77,'بم',21,'802');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (78,'بمپور',16,'1120');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (79,'بن',9,'1409');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (80,'بناب',1,'312');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (81,'بندرانزلی',25,'103');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (82,'بندرعباس',29,'2202');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (83,'بندرگز',24,'2701');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (84,'بندرلنگه',29,'2203');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (85,'بندرماهشهر',13,'605');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (86,'بو یین و میاندشت',4,'1024');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (87,'بوانات',17,'716');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (88,'بوشهر',7,'1801');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (89,'بوکان',2,'410');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (90,'بویراحمد',23,'1701');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (91,'بویین زهرا',18,'2601');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (92,'بهاباد',31,'2111');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (93,'بهار',30,'1307');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (94,'بهارستان',8,'2319');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (95,'بهبهان',13,'606');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (96,'بهشهر',27,'204');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (97,'بهمیی',23,'1705');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (98,'بیجار',20,'1202');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (99,'بیرجند',10,'2901');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (100,'بیضا',17,'731');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (101,'بیله سوار',3,'2402');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (102,'بینالود',11,'932');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (103,'پارس آباد',3,'2406');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (104,'پارسیان',29,'2211');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (105,'پاسارگاد',17,'723');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (106,'پاکدشت',8,'2313');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (107,'پاوه',22,'503');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (108,'پردیس',8,'2320');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (109,'پلدختر',26,'1508');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (110,'پلدشت',2,'415');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (111,'پیرانشهر',2,'402');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (112,'پیشوا',8,'2318');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (113,'تاکستان',18,'2602');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (114,'تایباد',11,'904');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (115,'تبریز',1,'303');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (116,'تربت جام',11,'906');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (117,'تربت حیدریه',11,'905');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (118,'ترکمن',24,'2702');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (119,'تفت',31,'2103');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (120,'تفتان',16,'1121');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (121,'تفرش',28,'3');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (122,'تکاب',2,'412');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (123,'تنکابن',27,'205');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (124,'تنگستان',7,'1802');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (125,'تویسرکان',30,'1301');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (126,'تهران',8,'2301');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (127,'تیران وکرون',4,'1019');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (128,'ثلاث باباجانی',22,'512');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (129,'جاجرم',12,'2803');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (130,'جاسک',29,'2206');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (131,'جغتای',11,'934');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (132,'جلفا',1,'319');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (133,'جم',7,'1809');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (134,'جوانرود',22,'509');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (135,'جویبار',27,'221');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (136,'جوین',11,'936');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (137,'جهرم',17,'704');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (138,'جیرفت',21,'803');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (139,'چادگان',4,'1020');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (140,'چاراویماق',1,'323');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (141,'چالدران',2,'414');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (142,'چالوس',27,'220');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (143,'چاه بهار',16,'1102');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (144,'چایپاره',2,'416');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (145,'چرام',23,'1706');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (146,'چرداول',6,'1604');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (147,'چگنی',26,'1510');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (148,'چناران',11,'918');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (149,'حاجی اباد',29,'2208');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (150,'حمیدیه',13,'625');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (151,'خاتم',31,'2109');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (152,'خاش',16,'1103');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (153,'خانمیرزا',9,'1410');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (154,'خداآفرین',1,'326');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (155,'خدابنده',14,'1903');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (156,'خرامه',17,'729');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (157,'خرم آباد',26,'1503');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (158,'خرم بید',17,'718');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (159,'خرمدره',14,'1907');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (160,'خرمشهر',13,'607');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (161,'خفر',17,'734');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (162,'خلخال',3,'2403');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (163,'خلیل آباد',11,'929');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (164,'خمیر',29,'2210');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (165,'خمین',28,'4');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (166,'خمینی شهر',4,'1003');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (167,'خنج',17,'724');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (168,'خنداب',28,'12');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (169,'خواف',11,'919');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (170,'خوانسار',4,'1004');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (171,'خور و بیابانک',4,'1023');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (172,'خوسف',10,'2910');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (173,'خوشاب',11,'938');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (174,'خوی',2,'403');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (175,'داراب',17,'705');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (176,'دالاهو',22,'513');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (177,'دامغان',15,'2001');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (178,'داورزن',11,'939');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (179,'درگز',11,'907');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (180,'درگزین',30,'1310');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (181,'درمیان',10,'2902');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (182,'دره شهر',6,'1602');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (183,'دزفول',13,'608');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (184,'دشت آزادگان',13,'609');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (185,'دشتستان',7,'1803');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (186,'دشتی',7,'1804');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (187,'دشتیاری',16,'1122');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (188,'دلفان',26,'1504');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (189,'دلگان',16,'1112');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (190,'دلیجان',28,'5');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (191,'دماوند',8,'2302');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (192,'دنا',23,'1704');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (193,'دورود',26,'1505');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (194,'دهاقان',4,'1021');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (195,'دهگلان',20,'1210');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (196,'دهلران',6,'1603');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (197,'دیر',7,'1805');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (198,'دیلم',7,'1808');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (199,'دیواندره',20,'1207');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (200,'رابر',21,'818');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (201,'راز و جرگلان',12,'2808');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (202,'راسک',16,'1108');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (203,'رامسر',27,'206');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (204,'رامشیر',13,'619');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (205,'رامهرمز',13,'610');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (206,'رامیان',24,'2711');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (207,'راور',21,'811');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (208,'رباط کریم',8,'2312');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (209,'رزن',30,'1308');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (210,'رستم',17,'726');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (211,'رشت',25,'105');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (212,'رشتخوار',11,'927');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (213,'رضوانشهر',25,'114');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (214,'رفسنجان',21,'804');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (215,'روانسر',22,'514');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (216,'رودان',29,'2207');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (217,'رودبار',25,'106');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (218,'رودبارجنوب',21,'815');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (219,'رودسر',25,'107');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (220,'رومشکان',26,'1511');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (221,'ری',8,'2303');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (222,'ریگان',21,'817');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (223,'زابل',16,'1104');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (224,'زاوه',11,'935');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (225,'زاهدان',16,'1105');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (226,'زرقان',17,'730');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (227,'زرند',21,'805');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (228,'زرندیه',28,'10');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (229,'زرین دشت',17,'719');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (230,'زنجان',14,'1904');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (231,'زهک',16,'1110');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (232,'زیرکوه',10,'2909');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (233,'ساری',27,'207');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (234,'سامان',9,'1408');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (235,'ساوجبلاغ',5,'3002');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (236,'ساوه',28,'6');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (237,'سبزوار',11,'908');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (238,'سپیدان',17,'706');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (239,'سراب',1,'305');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (240,'سراوان',16,'1106');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (241,'سرایان',10,'2906');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (242,'سرباز',16,'1123');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (243,'سربیشه',10,'2903');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (244,'سرپل ذهاب',22,'504');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (245,'سرچهان',17,'732');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (246,'سرخس',11,'920');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (247,'سرخه',15,'2008');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (248,'سردشت',2,'404');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (249,'سرعین',3,'2410');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (250,'سروآباد',20,'1209');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (251,'سروستان',17,'725');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (252,'سقز',20,'1203');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (253,'سلسله',26,'1509');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (254,'سلطانیه',14,'1910');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (255,'سلماس',2,'405');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (256,'سمنان',15,'2002');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (257,'سمیرم',4,'1005');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (258,'سنقر',22,'505');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (259,'سنندج',20,'1204');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (260,'سوادکوه',27,'208');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (261,'سوادکوه شمالی',27,'227');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (262,'سیاهکل',25,'115');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (263,'سیب و سوران',16,'1114');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (264,'سیرجان',21,'806');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (265,'سیروان',6,'1609');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (266,'سیریک',29,'2212');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (267,'سیمرغ',27,'226');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (268,'شادگان',13,'611');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (269,'شازند',28,'7');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (270,'شاهرود',15,'2003');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (271,'شاهین دژ',2,'411');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (272,'شاهین شهرومیمه',4,'1016');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (273,'شبستر',1,'314');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (274,'شفت',25,'112');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (275,'شمیرانات',8,'2304');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (276,'شوش',13,'614');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (277,'شوشتر',13,'612');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (278,'شوط',2,'417');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (279,'شهربابک',21,'807');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (280,'شهرضا',4,'1009');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (281,'شهرکرد',9,'1402');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (282,'شهریار',8,'2309');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (283,'شیراز',17,'707');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (284,'شیروان',12,'2804');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (285,'صالح آباد',11,'940');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (286,'صحنه',22,'510');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (287,'صومعه سرا',25,'108');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (288,'طارم',14,'1908');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (289,'طالقان',5,'3004');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (290,'طبس',10,'2911');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (291,'طوالش',25,'104');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (292,'عباس آباد',27,'224');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (293,'عجب شیر',1,'325');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (294,'عسلویه',7,'1810');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (295,'علی آباد کتول',24,'2703');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (296,'عنبرآباد',21,'812');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (297,'فارسان',9,'1403');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (298,'فاروج',12,'2805');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (299,'فاریاب',21,'822');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (300,'فامنین',30,'1309');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (301,'فراشبند',17,'722');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (302,'فراهان',28,'13');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (303,'فردوس',10,'2907');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (304,'فردیس',5,'3006');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (305,'فریدن',4,'1006');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (306,'فریدونشهر',4,'1007');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (307,'فریدونکنار',27,'223');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (308,'فریمان',11,'922');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (309,'فسا',17,'708');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (310,'فلاورجان',4,'1008');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (311,'فنوج',16,'1119');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (312,'فومن',25,'109');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (313,'فهرج',21,'819');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (314,'فیروزآباد',17,'709');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (315,'فیروزکوه',8,'2314');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (316,'فیروزه',11,'933');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (317,'قایم شهر',27,'210');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (318,'قاینات',10,'2904');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (319,'قدس',8,'2316');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (320,'قرچک',8,'2321');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (321,'قروه',20,'1205');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (322,'قزوین',18,'2603');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (323,'قشم',29,'2204');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (324,'قصرشیرین',22,'506');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (325,'قصرقند',16,'1118');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (326,'قلعه گنج',21,'816');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (327,'قم',19,'2501');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (328,'قوچان',11,'913');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (329,'قیروکارزین',17,'720');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (330,'کارون',13,'627');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (331,'کازرون',17,'710');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (332,'کاشان',4,'1010');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (333,'کاشمر',11,'914');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (334,'کامیاران',20,'1208');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (335,'کبودرآهنگ',30,'1305');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (336,'کرج',5,'3001');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (337,'کردکوی',24,'2704');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (338,'کرمان',21,'808');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (339,'کرمانشاه',22,'502');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (340,'کلات',11,'928');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (341,'کلاردشت',27,'228');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (342,'کلاله',24,'2709');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (343,'کلیبر',1,'315');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (344,'کمیجان',28,'11');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (345,'کنارک',16,'1109');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (346,'کنگان',7,'1806');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (347,'کنگاور',22,'507');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (348,'کوار',17,'728');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (349,'کوثر',3,'2407');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (350,'کوه چنار',17,'733');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (351,'کوهبنان',21,'814');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (352,'کوهدشت',26,'1506');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (353,'کوهرنگ',9,'1406');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (354,'کوهسرخ',11,'941');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (355,'کهگیلویه',23,'1702');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (356,'کهنوج',21,'809');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (357,'کیار',9,'1407');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (358,'گالیکش',24,'2714');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (359,'گتوند',13,'620');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (360,'گچساران',23,'1703');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (361,'گراش',17,'727');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (362,'گرگان',24,'2705');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (363,'گرمسار',15,'2004');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (364,'گرمه',12,'2807');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (365,'گرمی',3,'2405');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (366,'گلپایگان',4,'1011');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (367,'گلوگاه',27,'222');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (368,'گمیشان',24,'2713');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (369,'گناباد',11,'915');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (370,'گناوه',7,'1807');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (371,'گنبدکاووس',24,'2706');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (372,'گیلانغرب',22,'508');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (373,'لارستان',17,'711');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (374,'لالی',13,'617');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (375,'لامرد',17,'715');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (376,'لاهیجان',25,'111');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (377,'لردگان',9,'1404');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (378,'لنجان',4,'1012');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (379,'لنده',23,'1708');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (380,'لنگرود',25,'110');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (381,'مارگون',23,'1709');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (382,'ماسال',25,'116');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (383,'ماکو',2,'406');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (384,'مانه وسملقان',12,'2806');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (385,'ماهنشان',14,'1909');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (386,'مبارکه',4,'1017');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (387,'محلات',28,'9');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (388,'محمودآباد',27,'218');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (389,'مراغه',1,'306');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (390,'مراوه تپه',24,'2712');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (391,'مرند',1,'307');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (392,'مرودشت',17,'712');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (393,'مریوان',20,'1206');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (394,'مسجدسلیمان',13,'613');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (395,'مشگین شهر',3,'2404');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (396,'مشهد',11,'916');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (397,'ملارد',8,'2317');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (398,'ملایر',30,'1302');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (399,'ملکان',1,'320');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (400,'ملکشاهی',6,'1608');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (401,'ممسنی',17,'713');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (402,'منوجان',21,'813');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (403,'مه ولات',11,'930');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (404,'مهاباد',2,'407');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (405,'مهدی شهر',15,'2005');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (406,'مهر',17,'721');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (407,'مهران',6,'1605');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (408,'مهرستان',16,'1113');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (409,'مهریز',31,'2104');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (410,'میامی',15,'2007');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (411,'میاندوآب',2,'408');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (412,'میاندورود',27,'225');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (413,'میانه',1,'310');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (414,'میبد',31,'2106');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (415,'میرجاوه',16,'1117');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (416,'میناب',29,'2205');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (417,'مینودشت',24,'2707');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (418,'نایین',4,'1013');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (419,'نجف آباد',4,'1014');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (420,'نرماشیر',21,'821');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (421,'نطنز',4,'1015');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (422,'نظرآباد',5,'3003');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (423,'نقده',2,'409');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (424,'نکا',27,'219');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (425,'نمین',3,'2408');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (426,'نور',27,'214');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (427,'نوشهر',27,'215');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (428,'نهاوند',30,'1303');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (429,'نهبندان',10,'2905');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (430,'نی ریز',17,'714');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (431,'نیر',3,'2409');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (432,'نیشابور',11,'917');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (433,'نیک شهر',16,'1107');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (434,'نیمروز',16,'1115');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (435,'ورامین',8,'2306');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (436,'ورزقان',1,'324');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (437,'هامون',16,'1116');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (438,'هرسین',22,'511');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (439,'هریس',1,'316');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (440,'هشترود',1,'311');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (441,'هفتکل',13,'622');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (442,'هلیلان',6,'1611');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (443,'همدان',30,'1304');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (444,'هندیجان',13,'618');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (445,'هوراند',1,'327');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (446,'هویزه',13,'623');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (447,'هیرمند',16,'1111');
INSERT INTO `township` (`id`, `name`,`province_id`,`amar_code`) VALUES (448,'یزد',31,'2105');